# Generated by Django 5.2.3 on 2025-06-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        ('user_app', '0002_remove_profile_avatar_remove_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administered_group', to='user_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/group_avatars'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/messages'),
        ),
    ]
