# Generated by Django 5.2.3 on 2025-06-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='album',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post_app.tag'),
            preserve_default=False,
        ),
    ]
